# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20160123_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
