# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20160209_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.CharField(max_length=100),
        ),
    ]
