# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20160209_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
